name: Reminder notification
on:
  schedule:
    - cron: '0 14 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Reminder API
      - uses: actions/checkout@v2
      - run: |
          curl --request GET \
          --url 'https://${{ secrets.MAIN_SITE }}/api/reminder?key=${{ secrets.TELEGRAM_API_KEY }}'
      - uses: gautamkrishnar/keepalive-workflow@v1 
